In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
stock_symbol = "AAPL"
data = pd.read_csv('csv/' + str(stock_symbol) + '.timeseries.csv', date_parser = True)
data.tail()

,date,open,high,low,close,volume,adjclose
9840,1980-12-18,0.475446,0.477679,0.475446,0.475446,18362400.0,0.377609
9841,1980-12-17,0.462054,0.464286,0.462054,0.462054,21610400.0,0.366972
9842,1980-12-16,0.453125,0.453125,0.450893,0.450893,26432000.0,0.358108
9843,1980-12-15,0.488839,0.488839,0.486607,0.486607,43971200.0,0.386473
9844,1980-12-12,0.513393,0.515625,0.513393,0.513393,117258400.0,0.407747

In [3]:
data_training = data[data['date'] < '2019-01-01'].sort_values(by='date', ascending=True).copy()
data_training

,date,open,high,low,close,volume,adjclose
9844,1980-12-12,0.513393,0.515625,0.513393,0.513393,117258400.0,0.407747
9843,1980-12-15,0.488839,0.488839,0.486607,0.486607,43971200.0,0.386473
9842,1980-12-16,0.453125,0.453125,0.450893,0.450893,26432000.0,0.358108
9841,1980-12-17,0.462054,0.464286,0.462054,0.462054,21610400.0,0.366972
9840,1980-12-18,0.475446,0.477679,0.475446,0.475446,18362400.0,0.377609
9839,1980-12-19,0.504464,0.506696,0.504464,0.504464,12157600.0,0.400656
9838,1980-12-22,0.529018,0.531250,0.529018,0.529018,9340800.0,0.420157
9837,1980-12-23,0.551339,0.553571,0.551339,0.551339,11737600.0,0.437885
9836,1980-12-24,0.580357,0.582589,0.580357,0.580357,12000800.0,0.460931
9835,1980-12-26,0.633929,0.636161,0.633929,0.633929,13893600.0,0.503479
9834,1980-12-29,0.642857,0.645089,0.642857,0.642857,23290400.0,0.510570
9833,1980-12-30,0.629464,0.629464,0.627232,0.627232,17220000.0,0.498160
9832,1980-12-31,0.611607,0.611607,0.609375,0.609375,8937600.0,0.483978
9831,1981-01-02,0.616071,0.620536,0.616071,0.616071,5415200.0,0.489296
9830,1981-01-05,0.604911,0.604911,0.602679,0.602679,8932000.0,0.478659
9829,1981-01-06,0.578125,0.578125,0.575893,0.575893,11289600.0,0.457386
9828,1981-01-07,0.553571,0.553571,0.551339,0.551339,13921600.0,0.437885
9827,1981-01-08,0.542411,0.542411,0.540179,0.540179,9956800.0,0.429021
9826,1981-01-09,0.569196,0.571429,0.569196,0.569196,5376000.0,0.452067
9825,1981-01-12,0.569196,0.569196,0.564732,0.564732,5924800.0,0.448522
9824,1981-01-13,0.546875,0.546875,0.544643,0.544643,5762400.0,0.432566
9823,1981-01-14,0.546875,0.549107,0.546875,0.546875,3572800.0,0.434339
9822,1981-01-15,0.558036,0.562500,0.558036,0.558036,3516800.0,0.443203
9821,1981-01-16,0.555804,0.555804,0.553571,0.553571,3348800.0,0.439657
9820,1981-01-19,0.587054,0.589286,0.587054,0.587054,10393600.0,0.466250
9819,1981-01-20,0.571429,0.571429,0.569196,0.569196,7520800.0,0.452067
9818,1981-01-21,0.580357,0.584821,0.580357,0.580357,3976000.0,0.460931
9817,1981-01-22,0.587054,0.591518,0.587054,0.587054,8887200.0,0.466250
9816,1981-01-23,0.587054,0.589286,0.584821,0.584821,2805600.0,0.464477
9815,1981-01-26,0.578125,0.578125,0.575893,0.575893,6160000.0,0.457386
...,...,...,...,...,...,...,...
279,2018-11-15,188.389999,191.970001,186.899994,191.410004,46478800.0,188.576630
278,2018-11-16,190.500000,194.970001,189.460007,193.529999,36928300.0,190.665237
277,2018-11-19,190.000000,190.699997,184.990005,185.860001,41925300.0,183.108780
276,2018-11-20,178.369995,181.470001,175.509995,176.979996,67825200.0,174.360245
275,2018-11-21,179.729996,180.270004,176.550003,176.779999,31124200.0,174.163193
274,2018-11-23,174.940002,176.600006,172.100006,172.289993,23624000.0,169.739655
273,2018-11-26,174.240005,174.949997,170.259995,174.619995,44998500.0,172.035172
272,2018-11-27,171.509995,174.770004,170.880005,174.240005,41387400.0,171.660797
271,2018-11-28,176.729996,181.289993,174.929993,180.940002,46062500.0,178.261627
270,2018-11-29,182.660004,182.800003,177.699997,179.550003,41770000.0,176.892197
269,2018-11-30,180.289993,180.330002,177.029999,178.580002,39531500.0,175.936554
268,2018-12-03,184.460007,184.940002,181.210007,184.820007,40802500.0,182.084183
267,2018-12-04,180.949997,182.389999,176.270004,176.690002,41344300.0,174.074539
266,2018-12-06,171.759995,174.779999,170.419998,174.720001,43098400.0,172.133682
265,2018-12-07,173.490005,174.490005,168.300003,168.490005,42281600.0,165.995926
264,2018-12-10,165.000000,170.089996,163.330002,169.600006,62026000.0,167.089478
263,2018-12-11,171.660004,171.789993,167.000000,168.630005,47281700.0,166.133850
262,2018-12-12,170.399994,171.919998,169.020004,169.100006,35627700.0,166.596878
261,2018-12-13,170.490005,172.570007,169.550003,170.949997,31898600.0,168.419479
260,2018-12-14,169.000000,169.080002,165.279999,165.479996,40703700.0,163.030457
259,2018-12-17,165.449997,168.350006,162.729996,163.940002,44287900.0,161.513260
258,2018-12-18,165.380005,167.529999,164.389999,166.070007,33841500.0,163.611740
257,2018-12-19,166.000000,167.449997,159.089996,160.889999,49047300.0,158.508408
256,2018-12-20,160.399994,162.110001,155.300003,156.830002,64773000.0,154.508499
255,2018-12-21,156.860001,158.160004,149.630005,150.729996,95744600.0,148.498795
254,2018-12-24,148.149994,151.550003,146.589996,146.830002,37169200.0,144.656540
253,2018-12-26,148.300003,157.229996,146.720001,157.169998,58582500.0,154.843475
252,2018-12-27,155.839996,156.770004,150.070007,156.149994,53117100.0,153.838562
251,2018-12-28,157.500000,158.520004,154.550003,156.229996,42291400.0,153.917389
250,2018-12-31,158.529999,159.360001,156.479996,157.740005,35003500.0,155.405045

In [4]:
data_test = data[data['date'] >= '2019-01-01'].sort_values(by='date', ascending=True).copy()
data_test

,date,open,high,low,close,volume,adjclose
249,2019-01-02,154.889999,158.850006,154.229996,157.919998,37039700.0,155.582367
248,2019-01-03,143.979996,145.720001,142.000000,142.190002,91312200.0,140.085220
247,2019-01-04,144.529999,148.550003,143.800003,148.259995,58607100.0,146.065353
246,2019-01-07,148.699997,148.830002,145.899994,147.929993,54777800.0,145.740265
245,2019-01-08,149.559998,151.820007,148.520004,150.750000,41025300.0,148.518509
244,2019-01-09,151.289993,154.529999,149.630005,153.309998,45099100.0,151.040604
243,2019-01-10,152.500000,153.970001,150.860001,153.800003,35780700.0,151.523376
242,2019-01-11,152.880005,153.699997,151.509995,152.289993,27023200.0,150.035706
241,2019-01-14,150.850006,151.270004,149.220001,150.000000,32439200.0,147.779602
240,2019-01-15,150.270004,153.389999,150.050003,153.070007,28710900.0,150.804169
239,2019-01-16,153.080002,155.880005,153.000000,154.940002,30569700.0,152.646484
238,2019-01-17,154.199997,157.660004,153.259995,155.860001,29821200.0,153.552872
237,2019-01-18,157.500000,157.880005,155.979996,156.820007,33751000.0,154.498657
236,2019-01-22,156.410004,156.729996,152.619995,153.300003,30394000.0,151.030777
235,2019-01-23,154.149994,155.139999,151.699997,153.919998,23130600.0,151.641586
234,2019-01-24,154.110001,154.479996,151.740005,152.699997,25441500.0,150.439636
233,2019-01-25,155.479996,158.130005,154.320007,157.759995,33535500.0,155.424744
232,2019-01-28,155.789993,156.330002,153.660004,156.300003,26192100.0,153.986359
231,2019-01-29,156.250000,158.130005,154.110001,154.679993,41587200.0,152.390320
230,2019-01-30,163.250000,166.149994,160.229996,165.250000,61109800.0,162.803864
229,2019-01-31,166.110001,169.000000,164.559998,166.440002,40739600.0,163.976242
228,2019-02-01,166.960007,168.979996,165.929993,166.520004,32668100.0,164.055069
227,2019-02-04,167.410004,171.660004,167.279999,171.250000,31495500.0,168.715042
226,2019-02-05,172.860001,175.080002,172.350006,174.179993,36101600.0,171.601685
225,2019-02-06,174.649994,175.570007,172.850006,174.240005,28239600.0,171.660797
224,2019-02-07,172.399994,173.940002,170.339996,170.940002,31741700.0,168.409653
223,2019-02-08,168.990005,170.660004,168.419998,170.410004,23820000.0,168.607529
222,2019-02-11,171.050003,171.210007,169.250000,169.429993,20993400.0,167.637878
221,2019-02-12,170.100006,171.000000,169.699997,170.889999,22283500.0,169.082443
220,2019-02-13,171.389999,172.479996,169.919998,170.179993,22490200.0,168.379944
...,...,...,...,...,...,...,...
29,2019-11-14,263.750000,264.880005,262.100006,262.640015,22295700.0,262.640015
28,2019-11-15,263.679993,265.779999,263.010010,265.760010,25051600.0,265.760010
27,2019-11-18,265.799988,267.429993,264.230011,267.100006,21675800.0,267.100006
26,2019-11-19,267.899994,268.000000,265.390015,266.290009,19041800.0,266.290009
25,2019-11-20,265.540009,266.079987,260.399994,263.190002,26558600.0,263.190002
24,2019-11-21,263.690002,264.010010,261.179993,262.010010,30348800.0,262.010010
23,2019-11-22,262.589996,263.179993,260.839996,261.779999,16331300.0,261.779999
22,2019-11-25,262.709991,266.440002,262.519989,266.369995,21005100.0,266.369995
21,2019-11-26,266.940002,267.160004,262.500000,264.290009,26301900.0,264.290009
20,2019-11-27,265.579987,267.980011,265.309998,267.839996,16308900.0,267.839996
19,2019-11-29,266.600006,268.000000,265.899994,267.250000,11654400.0,267.250000
18,2019-12-02,267.269989,268.250000,263.450012,264.160004,23621800.0,264.160004
17,2019-12-03,258.309998,259.529999,256.290009,259.450012,28607600.0,259.450012
16,2019-12-04,261.070007,263.309998,260.679993,261.739990,16795400.0,261.739990
15,2019-12-05,263.790009,265.890015,262.730011,265.579987,18606100.0,265.579987
14,2019-12-06,267.480011,271.000000,267.299988,270.709991,26518900.0,270.709991
13,2019-12-09,270.000000,270.799988,264.910004,266.920013,32010600.0,266.920013
12,2019-12-10,268.600006,270.070007,265.859985,268.480011,22605100.0,268.480011
11,2019-12-11,268.809998,271.100006,268.500000,270.769989,19689200.0,270.769989
10,2019-12-12,267.779999,272.559998,267.320007,271.459991,34327600.0,271.459991
9,2019-12-13,271.459991,275.299988,270.929993,275.149994,33396900.0,275.149994
8,2019-12-16,277.000000,280.790009,276.980011,279.859985,32046500.0,279.859985
7,2019-12-17,279.570007,281.769989,278.799988,280.410004,28539600.0,280.410004
6,2019-12-18,279.799988,281.899994,279.119995,279.739990,29007100.0,279.739990
5,2019-12-19,279.500000,281.179993,278.950012,280.019989,24592300.0,280.019989
4,2019-12-20,282.230011,282.649994,278.559998,279.440002,68994500.0,279.440002
3,2019-12-23,280.529999,284.250000,280.369995,284.000000,24643000.0,284.000000
2,2019-12-24,284.690002,284.890015,282.920013,284.269989,12119700.0,284.269989
1,2019-12-26,284.820007,289.980011,284.700012,289.910004,23280300.0,289.910004
0,2019-12-27,291.119995,293.970001,288.119995,289.799988,36566500.0,289.799988

In [5]:
training_data = data_training.drop(['date', 'adjclose'], axis = 1)
training_data.head()

          open      high       low     close       volume
9844  0.513393  0.515625  0.513393  0.513393  117258400.0
9843  0.488839  0.488839  0.486607  0.486607   43971200.0
9842  0.453125  0.453125  0.450893  0.450893   26432000.0
9841  0.462054  0.464286  0.462054  0.462054   21610400.0
9840  0.475446  0.477679  0.475446  0.475446   18362400.0

In [6]:
scaler = MinMaxScaler()
training_data = scaler.fit_transform(training_data)
training_data

array([[0.00136495, 0.00135878, 0.00138061, 0.00136697, 0.06302277],
       [0.00125847, 0.00124395, 0.00126393, 0.00125145, 0.02351618],
       [0.00110358, 0.00109085, 0.00110837, 0.00109743, 0.01406141],
       ...,
       [0.67499537, 0.67119837, 0.6528062 , 0.67258015, 0.02844642],
       [0.68219458, 0.67870036, 0.67231978, 0.67292517, 0.02261066],
       [0.68666155, 0.6823013 , 0.68072627, 0.67943738, 0.01868201]])

In [7]:
x_train = []
y_train = []

In [8]:
training_data.shape[0]

9595

In [9]:
for i in range(60, training_data.shape[0]):
    x_train.append(training_data[i-60:i])
    y_train.append(training_data[i, 0])

In [10]:
x_train, y_train = np.array(x_train), np.array(y_train)

In [11]:
x_train.shape, y_train.shape

((9535, 60, 5), (9535,))

In [12]:
### Building LSTM

In [13]:
from keras import Sequential
from keras.layers import Dense, LSTM, Dropout

Using Theano backend.

In [14]:
regressior = Sequential()

regressior.add(LSTM(units = 60, activation = 'relu', return_sequences = True, input_shape = (x_train.shape[1], 5)))
regressior.add(Dropout(0.2))
               
regressior.add(LSTM(units = 60, activation = 'relu', return_sequences = True))
regressior.add(Dropout(0.2))

regressior.add(LSTM(units = 80, activation = 'relu', return_sequences = True))
regressior.add(Dropout(0.2))

regressior.add(LSTM(units = 120, activation = 'relu'))
regressior.add(Dropout(0.2))

regressior.add(Dense(units = 1))

In [15]:
regressior.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_1 (LSTM)                (None, 60, 60)            15840
_________________________________________________________________
dropout_1 (Dropout)          (None, 60, 60)            0
_________________________________________________________________
lstm_2 (LSTM)                (None, 60, 60)            29040
_________________________________________________________________
dropout_2 (Dropout)          (None, 60, 60)            0
_________________________________________________________________
lstm_3 (LSTM)                (None, 60, 80)            45120
_________________________________________________________________
dropout_3 (Dropout)          (None, 60, 80)            0
_________________________________________________________________
lstm_4 (LSTM)                (None, 120)               96480
_________________________________________________________________
dropout_4 (Dropout)          (None, 120)               0
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 121
=================================================================
Total params: 186,601
Trainable params: 186,601
Non-trainable params: 0
_________________________________________________________________

In [16]:
regressior.compile(optimizer='sgd', metrics=['mae', 'acc'], loss = 'mean_squared_error')

In [ ]:
regressior.fit(x_train, y_train, epochs=10, batch_size=32)

C:\Users\reggl\Anaconda3\lib\site-packages\theano\scan_module\scan_perform_ext.py:76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  "The file scan_perform.c is not available. This do"
C:\Users\reggl\Anaconda3\lib\site-packages\theano\scan_module\scan_perform_ext.py:76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  "The file scan_perform.c is not available. This do"
C:\Users\reggl\Anaconda3\lib\site-packages\theano\scan_module\scan_perform_ext.py:76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  "The file scan_perform.c is not available. This do"
C:\Users\reggl\Anaconda3\lib\site-packages\theano\scan_module\scan_perform_ext.py:76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  "The file scan_perform.c is not available. This do"
C:\Users\reggl\Anaconda3\lib\site-packages\theano\scan_module\scan_perform_ext.py:76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  "The file scan_perform.c is not available. This do"
C:\Users\reggl\Anaconda3\lib\site-packages\theano\scan_module\scan_perform_ext.py:76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  "The file scan_perform.c is not available. This do"
C:\Users\reggl\Anaconda3\lib\site-packages\theano\scan_module\scan_perform_ext.py:76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  "The file scan_perform.c is not available. This do"
C:\Users\reggl\Anaconda3\lib\site-packages\theano\scan_module\scan_perform_ext.py:76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.
  "The file scan_perform.c is not available. This do"

Epoch 1/10
9535/9535 [==============================] - 89s 9ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 2/10
9535/9535 [==============================] - 58s 6ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 3/10
9535/9535 [==============================] - 66s 7ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 4/10
9535/9535 [==============================] - 64s 7ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 5/10
9535/9535 [==============================] - 63s 7ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 6/10
9535/9535 [==============================] - 64s 7ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 7/10
9535/9535 [==============================] - 64s 7ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 8/10
9535/9535 [==============================] - 64s 7ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 9/10
9535/9535 [==============================] - 64s 7ms/step - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00
Epoch 10/10
6432/9535 [===================>..........] - ETA: 20s - loss: nan - mean_absolute_error: nan - acc: 0.0000e+00

In [ ]:
### Prepare test dataset

In [ ]:
data_test.tail()

In [ ]:
data_training.tail(60)

In [ ]:
past_60_days = data_training.tail(60)

In [ ]:
df = past_60_days.append(data_test, ignore_index = True)
df = df.drop(['date', 'adjclose'], axis = 1)
df.head()

In [ ]:
inputs = scaler.transform(df)
inputs

In [ ]:
x_test = []
y_test = []

for i in range(60, inputs.shape[0]):
    x_test.append(inputs[i-60:i])
    y_test.append(inputs[i, 0])

In [ ]:
x_test, y_test = np.array(x_test),np.array(y_test)
x_test.shape, y_test.shape

In [ ]:
y_pred = regressior.predict(x_test)

In [ ]:
scaler.scale_

In [ ]:
scale = 1/8.67066133e-03
scale

In [ ]:
y_pred = y_pred*scale
y_test = y_test*scale

In [ ]:
### Visualize Data

In [ ]:
plt.figure(figsize=(20,5))
plt.plot(y_test, color = 'red', label = 'Real ' + str(stock_symbol) + ' stock price')
plt.plot(y_pred, color = 'blue', label = 'Predicted ' + str(stock_symbol) + ' stock price')
plt.title(str(stock_symbol) + ' Prediction Chart 2019')
plt.grid(color='y', linestyle='-', linewidth=1)
plt.xlabel('Time')
plt.ylabel(str(stock_symbol) + ' stock price')
plt.legend()
plt.show()