In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = pd.read_csv('timeseries.csv', date_parser = True)
data.tail()

            date      open      high       low     close      volume  adjclose
8514  1986-03-19  0.099826  0.100694  0.097222  0.098090    47894400  0.063107
8515  1986-03-18  0.102431  0.103299  0.098958  0.099826    67766400  0.064224
8516  1986-03-17  0.100694  0.103299  0.100694  0.102431   133171200  0.065899
8517  1986-03-14  0.097222  0.102431  0.097222  0.100694   308160000  0.064783
8518  1986-03-13  0.088542  0.101562  0.088542  0.097222  1031788800  0.062549

In [3]:
data_training = data[data['date'] < '2019-01-01'].sort_values(by='date', ascending=True).copy()
data_training

,date,open,high,low,close,volume,adjclose
8518,1986-03-13,0.088542,0.101562,0.088542,0.097222,1031788800,0.062549
8517,1986-03-14,0.097222,0.102431,0.097222,0.100694,308160000,0.064783
8516,1986-03-17,0.100694,0.103299,0.100694,0.102431,133171200,0.065899
8515,1986-03-18,0.102431,0.103299,0.098958,0.099826,67766400,0.064224
8514,1986-03-19,0.099826,0.100694,0.097222,0.098090,47894400,0.063107
8513,1986-03-20,0.098090,0.098090,0.094618,0.095486,58435200,0.061432
8512,1986-03-21,0.095486,0.097222,0.091146,0.092882,59990400,0.059756
8511,1986-03-24,0.092882,0.092882,0.089410,0.090278,65289600,0.058081
8510,1986-03-25,0.090278,0.092014,0.089410,0.092014,32083200,0.059198
8509,1986-03-26,0.092014,0.095486,0.091146,0.094618,22752000,0.060873
8508,1986-03-27,0.094618,0.096354,0.094618,0.096354,16848000,0.061990
8507,1986-03-31,0.096354,0.096354,0.093750,0.095486,12873600,0.061432
8506,1986-04-01,0.095486,0.095486,0.094618,0.094618,11088000,0.060873
8505,1986-04-02,0.094618,0.097222,0.094618,0.095486,27014400,0.061432
8504,1986-04-03,0.096354,0.098958,0.096354,0.096354,23040000,0.061990
8503,1986-04-04,0.096354,0.097222,0.096354,0.096354,26582400,0.061990
8502,1986-04-07,0.096354,0.097222,0.092882,0.094618,16560000,0.060873
8501,1986-04-08,0.094618,0.097222,0.094618,0.095486,10252800,0.061432
8500,1986-04-09,0.095486,0.098090,0.095486,0.097222,12153600,0.062549
8499,1986-04-10,0.097222,0.098958,0.095486,0.098090,13881600,0.063107
8498,1986-04-11,0.098958,0.101562,0.098958,0.099826,17222400,0.064224
8497,1986-04-14,0.099826,0.101562,0.099826,0.100694,12153600,0.064783
8496,1986-04-15,0.100694,0.100694,0.097222,0.100694,9302400,0.064783
8495,1986-04-16,0.100694,0.105035,0.099826,0.104167,31910400,0.067016
8494,1986-04-17,0.104167,0.105035,0.104167,0.105035,22003200,0.067575
8493,1986-04-18,0.105035,0.105035,0.100694,0.101562,21628800,0.065341
8492,1986-04-21,0.101562,0.102431,0.098958,0.101562,22924800,0.065341
8491,1986-04-22,0.101562,0.101562,0.099826,0.099826,15552000,0.064224
8490,1986-04-23,0.099826,0.100694,0.098958,0.100260,15609600,0.064503
8489,1986-04-24,0.100260,0.111979,0.099826,0.110243,62352000,0.070926
...,...,...,...,...,...,...,...
279,2018-11-15,104.989998,107.800003,103.910004,107.279999,38505200,105.716866
278,2018-11-16,107.080002,108.879997,106.800003,108.290001,33502100,106.712151
277,2018-11-19,108.269997,108.559998,103.550003,104.620003,44773900,103.095619
276,2018-11-20,101.800003,102.970001,99.349998,101.709999,64052500,100.228027
275,2018-11-21,103.599998,104.430000,102.239998,103.110001,28130600,101.607620
274,2018-11-23,102.169998,103.809998,102.000000,103.070000,13823100,101.568207
273,2018-11-26,104.790001,106.629997,104.580002,106.470001,32336200,104.918671
272,2018-11-27,106.269997,107.330002,105.360001,107.139999,29124500,105.578896
271,2018-11-28,107.889999,111.330002,107.860001,111.120003,46788500,109.500916
270,2018-11-29,110.330002,111.120003,109.029999,110.190002,28123200,108.584465
269,2018-11-30,110.699997,110.970001,109.360001,110.889999,33665600,109.274261
268,2018-12-03,113.000000,113.419998,110.730003,112.089996,34732800,110.456779
267,2018-12-04,111.940002,112.639999,108.209999,108.519997,45197000,106.938789
266,2018-12-06,105.820000,109.239998,105.000000,109.190002,49107400,107.599037
265,2018-12-07,108.379997,109.449997,104.300003,104.820000,45044900,103.292702
264,2018-12-10,104.800003,107.980003,103.889999,107.589996,40801500,106.022339
263,2018-12-11,109.800003,110.949997,107.440002,108.589996,42381900,107.007774
262,2018-12-12,110.889999,111.269997,109.040001,109.080002,36183000,107.490639
261,2018-12-13,109.580002,110.870003,108.629997,109.449997,31333400,107.855240
260,2018-12-14,108.250000,109.260002,105.500000,106.029999,47043100,104.485077
259,2018-12-17,105.410004,105.800003,101.709999,102.889999,56957300,101.390823
258,2018-12-18,103.750000,104.510002,102.519997,103.970001,49319200,102.455093
257,2018-12-19,103.650002,106.879997,101.349998,103.690002,68198200,102.179176
256,2018-12-20,103.050003,104.309998,98.779999,101.510002,70334200,100.030937
255,2018-12-21,101.629997,103.000000,97.459999,98.230003,111242100,96.798729
254,2018-12-24,97.680000,97.970001,93.980003,94.129997,43935200,92.758461
253,2018-12-26,95.139999,100.690002,93.959999,100.559998,51634800,99.094772
252,2018-12-27,99.300003,101.190002,96.400002,101.180000,49498500,99.705742
251,2018-12-28,102.089996,102.410004,99.519997,100.389999,38196300,98.927246
250,2018-12-31,101.290001,102.400002,100.440002,101.570000,33173800,100.090057

In [5]:
data_test = data[data['date'] >= '2019-01-01'].sort_values(by='date', ascending=True).copy()
data_test

,date,open,high,low,close,volume,adjclose
249,2019-01-02,99.550003,101.750000,98.940002,101.120003,35329300,99.646614
248,2019-01-03,100.099998,100.190002,97.199997,97.400002,42579100,95.980820
247,2019-01-04,99.720001,102.510002,98.930000,101.930000,44060600,100.444817
246,2019-01-07,101.639999,103.269997,100.980003,102.059998,35656100,100.572922
245,2019-01-08,103.040001,103.970001,101.709999,102.800003,31514400,101.302139
244,2019-01-09,103.860001,104.879997,103.239998,104.269997,32280800,102.750717
243,2019-01-10,103.220001,103.750000,102.379997,103.599998,30067600,102.090485
242,2019-01-11,103.190002,103.440002,101.639999,102.800003,28314200,101.302139
241,2019-01-14,101.900002,102.870003,101.260002,102.050003,28437100,100.563072
240,2019-01-15,102.510002,105.050003,101.879997,105.010002,31587600,103.479950
239,2019-01-16,105.260002,106.260002,104.959999,105.379997,29853900,103.844551
238,2019-01-17,105.000000,106.629997,104.760002,106.120003,28393000,104.573769
237,2019-01-18,107.459999,107.900002,105.910004,107.709999,37427600,106.140602
236,2019-01-22,106.750000,107.099998,104.860001,105.680000,32371300,104.140175
235,2019-01-23,106.120003,107.040001,105.339996,106.709999,25874300,105.155167
234,2019-01-24,106.860001,107.000000,105.339996,106.199997,23164800,104.652603
233,2019-01-25,107.239998,107.879997,106.199997,107.169998,31225600,105.608467
232,2019-01-28,106.260002,106.480003,104.660004,105.080002,29476700,103.548927
231,2019-01-29,104.879997,104.970001,102.169998,102.940002,31490500,101.440102
230,2019-01-30,104.620003,106.379997,104.330002,106.379997,49471900,104.829979
229,2019-01-31,103.800003,105.220001,103.180000,104.430000,55636400,102.908394
228,2019-02-01,103.779999,104.099998,102.349998,102.779999,35535700,101.282433
227,2019-02-04,102.870003,105.800003,102.769997,105.739998,31315100,104.199295
226,2019-02-05,106.059998,107.269997,105.959999,107.220001,27325400,105.657745
225,2019-02-06,107.000000,107.000000,105.529999,106.029999,20609800,104.485077
224,2019-02-07,105.190002,105.589996,104.290001,105.269997,29760700,103.736145
223,2019-02-08,104.389999,105.779999,104.260002,105.669998,21461100,104.130325
222,2019-02-11,106.199997,106.580002,104.970001,105.250000,18914100,103.716446
221,2019-02-12,106.139999,107.139999,105.480003,106.889999,25056600,105.332550
220,2019-02-13,107.500000,107.779999,106.709999,106.809998,18394900,105.253716
...,...,...,...,...,...,...,...
29,2019-11-14,147.020004,148.410004,147.000000,148.059998,19729800,147.557892
28,2019-11-15,148.929993,149.990005,148.270004,149.970001,23485700,149.461426
27,2019-11-18,150.070007,150.550003,148.979996,150.339996,21534000,149.830170
26,2019-11-19,150.880005,151.330002,150.199997,150.389999,23935700,149.879990
25,2019-11-20,150.309998,150.839996,148.460007,149.619995,25696800,149.619995
24,2019-11-21,149.399994,149.800003,148.500000,149.479996,18576100,149.479996
23,2019-11-22,150.070007,150.300003,148.820007,149.589996,15901800,149.589996
22,2019-11-25,150.000000,151.350006,149.919998,151.229996,22420900,151.229996
21,2019-11-26,151.360001,152.419998,151.320007,152.029999,24620100,152.029999
20,2019-11-27,152.330002,152.500000,151.520004,152.320007,15184400,152.320007
19,2019-11-29,152.100006,152.300003,151.279999,151.380005,11977300,151.380005
18,2019-12-02,151.809998,151.830002,148.320007,149.550003,27418400,149.550003
17,2019-12-03,147.490005,149.429993,146.649994,149.309998,24066000,149.309998
16,2019-12-04,150.139999,150.179993,149.199997,149.850006,17574700,149.850006
15,2019-12-05,150.050003,150.320007,149.479996,149.929993,17869100,149.929993
14,2019-12-06,150.990005,151.869995,150.270004,151.750000,16403500,151.750000
13,2019-12-09,151.070007,152.210007,150.910004,151.360001,16687400,151.360001
12,2019-12-10,151.289993,151.889999,150.759995,151.130005,16476100,151.130005
11,2019-12-11,151.539993,151.869995,150.330002,151.699997,18856600,151.699997
10,2019-12-12,151.649994,153.440002,151.020004,153.240005,24612100,153.240005
9,2019-12-13,153.000000,154.889999,152.830002,154.529999,23845400,154.529999
8,2019-12-16,155.110001,155.899994,154.820007,155.529999,24144200,155.529999
7,2019-12-17,155.449997,155.710007,154.449997,154.690002,25425600,154.690002
6,2019-12-18,154.300003,155.479996,154.179993,154.369995,24129200,154.369995
5,2019-12-19,154.000000,155.770004,153.750000,155.710007,24958900,155.710007
4,2019-12-20,157.350006,158.490005,156.289993,157.410004,53477500,157.410004
3,2019-12-23,158.119995,158.119995,157.270004,157.410004,17718200,157.410004
2,2019-12-24,157.479996,157.710007,157.119995,157.380005,8989200,157.380005
1,2019-12-26,157.559998,158.729996,157.399994,158.669998,14520600,158.669998
0,2019-12-27,159.449997,159.550003,158.220001,158.960007,18412800,158.960007

In [6]:
training_data = data_training.drop(['date', 'adjclose'], axis = 1)
training_data.head()

          open      high       low     close      volume
8518  0.088542  0.101562  0.088542  0.097222  1031788800
8517  0.097222  0.102431  0.097222  0.100694   308160000
8516  0.100694  0.103299  0.100694  0.102431   133171200
8515  0.102431  0.103299  0.098958  0.099826    67766400
8514  0.099826  0.100694  0.097222  0.098090    47894400

In [ ]:
scaler = MinMaxScaler()
training_data = scaler.fit_transform(training_data)
training_data

In [ ]:
x_train = []
y_train = []

In [ ]:
training_data.shape[0]

In [ ]:
for i in range(60, training_data.shape[0]):
    x_train.append(training_data[i-60:i])
    y_train.append(training_data[i, 0])

In [ ]:
x_train, y_train = np.array(x_train), np.array(y_train)

In [ ]:
x_train.shape, y_train.shape

In [ ]:
### Building LSTM

In [ ]:
from keras import Sequential
from keras.layers import Dense, LSTM, Dropout

In [ ]:
regressior = Sequential()

regressior.add(LSTM(units = 60, activation = 'relu', return_sequences = True, input_shape = (x_train.shape[1], 5)))
regressior.add(Dropout(0.2))
               
regressior.add(LSTM(units = 60, activation = 'relu', return_sequences = True))
regressior.add(Dropout(0.2))

regressior.add(LSTM(units = 80, activation = 'relu', return_sequences = True))
regressior.add(Dropout(0.2))

regressior.add(LSTM(units = 120, activation = 'relu'))
regressior.add(Dropout(0.2))

regressior.add(Dense(units = 1))

In [ ]:
regressior.summary()

In [ ]:
regressior.compile(optimizer='sgd', metrics=['accuracy'], loss = 'mean_squared_error')

In [ ]:
regressior.fit(x_train, y_train, epochs=10, batch_size=32)

In [ ]:
### Prepare test dataset

In [ ]:
data_test.tail()

In [ ]:
data_training.tail(60)

In [ ]:
past_60_days = data_training.tail(60)

In [ ]:
df = past_60_days.append(data_test, ignore_index = True)
df = df.drop(['date', 'adjclose'], axis = 1)
df.head()

In [ ]:
inputs = scaler.transform(df)
inputs

In [ ]:
x_test = []
y_test = []

for i in range(60, inputs.shape[0]):
    x_test.append(inputs[i-60:i])
    y_test.append(inputs[i, 0])

In [ ]:
x_test, y_test = np.array(x_test),np.array(y_test)
x_test.shape, y_test.shape

In [ ]:
y_pred = regressior.predict(x_test)

In [ ]:
scaler.scale_

In [ ]:
scale = 1/6.22161376e-03
scale

In [ ]:
y_pred = y_pred*scale
y_test = y_test*scale

In [ ]:
### Visualize Data

In [ ]:
plt.figure(figsize=(14,5))
plt.plot(y_test, color = 'red', label = 'Real IBM stock price')
plt.plot(y_pred, color = 'blue', label = 'Predicted IBM stock price')
plt.plot('IBM stock price prediction')
plt.xlabel('Time')
plt.ylabel('IBM stock price')
plt.legend()
plt.show()